# Generated by Django 3.2.15 on 2026-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email', models.BooleanField(default=False)),
                ('send_text_sms', models.BooleanField(default=False)),
                ('direct', models.BooleanField(default=False)),
                ('cancel_admission', models.BooleanField(default=False)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('admission_code', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='admission_images/')),
                ('admission_date', models.DateField()),
                ('candidate_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alternate_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionCourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField()),
                ('remarks', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to='certificate/logo/')),
                ('logo_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right')], default='top_center', max_length=20)),
                ('institute_name', models.CharField(blank=True, max_length=255)),
                ('institute_name_font_size', models.IntegerField(default=24)),
                ('institute_name_bold', models.BooleanField(default=True)),
                ('institute_name_italic', models.BooleanField(default=False)),
                ('institute_name_color', models.CharField(default='#000000', max_length=20)),
                ('institute_name_alignment', models.CharField(default='center', max_length=20)),
                ('certificate_title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('title_font_size', models.IntegerField(default=36)),
                ('title_bold', models.BooleanField(default=True)),
                ('title_italic', models.BooleanField(default=False)),
                ('title_color', models.CharField(default='#000000', max_length=20)),
                ('title_alignment', models.CharField(default='center', max_length=20)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_font_size', models.IntegerField(default=18)),
                ('body_color', models.CharField(default='#000000', max_length=20)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate/signature/')),
                ('signature_label', models.CharField(blank=True, max_length=100)),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='certificate/stamp/')),
                ('stamp_position', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='right', max_length=20)),
                ('border_style', models.CharField(choices=[('none', 'No Border'), ('simple', 'Simple Line Border'), ('decorative', 'Decorative Border')], default='simple', max_length=20)),
                ('border_color', models.CharField(default='#000000', max_length=20)),
                ('background_type', models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate/background/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
