# Generated by Django 3.2.15 on 2026-04-16 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('admission', '0001_initial'),
        ('master', '0001_initial'),
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateissue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certs_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.organization'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to='admission.admission'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admission.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateapproval',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_approval', to='admission.admission'),
        ),
        migrations.AddField(
            model_name='certificateapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateapproval',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.branch'),
        ),
        migrations.AddField(
            model_name='certificateapproval',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.organization'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='admission.admission'),
        ),
        migrations.AddField(
            model_name='admission',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='admissions', to='course.Batch'),
        ),
        migrations.AddField(
            model_name='admission',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.branch'),
        ),
        migrations.AddField(
            model_name='admission',
            name='courses',
            field=models.ManyToManyField(related_name='admissions', to='course.Course'),
        ),
        migrations.AddField(
            model_name='admission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.organization'),
        ),
        migrations.AddField(
            model_name='admission',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='student_details.registration'),
        ),
        migrations.AddField(
            model_name='admission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.userrole'),
        ),
        migrations.AddField(
            model_name='admission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('admission', 'date')},
        ),
    ]
