# Generated by Django 3.2.15 on 2026-05-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('admission', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='courses',
        ),
        migrations.CreateModel(
            name='AdmissionCourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_batches', to='admission.admission')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
