# Generated by Django 3.2.15 on 2026-05-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('admission', '0003_auto_20260506_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='course.course'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
