# Generated by Django 3.2.15 on 2026-05-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('admission', '0004_auto_20260511_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateissue',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.batch'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.course'),
        ),
    ]
