# Generated by Django 3.2.15 on 2026-06-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20260511_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='template_path',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/background/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_type',
            field=models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='body_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='body_font_size',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='border_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='border_style',
            field=models.CharField(choices=[('none', 'No Border'), ('simple', 'Simple Line Border'), ('decorative', 'Decorative Border')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='certificate_title',
            field=models.CharField(default='Certificate of Completion', max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institute_logo',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/logo/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institute_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institute_name_alignment',
            field=models.CharField(default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institute_name_bold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institute_name_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institute_name_font_size',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='institute_name_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='logo_position',
            field=models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right')], default='top_center', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/signature/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/stamp/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='stamp_position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='right', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_alignment',
            field=models.CharField(default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_bold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_font_size',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_italic',
            field=models.BooleanField(default=False),
        ),
    ]
