# Generated by Django 3.2.15 on 2026-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20260623_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
