# Generated by Django 3.2.15 on 2026-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20260623_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateissue',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/pdf/'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
