# Generated by Django 3.2.15 on 2026-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='is_branch_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='is_main_branch_admin',
            field=models.BooleanField(default=False),
        ),
    ]
