# Generated by Django 3.2.15 on 2026-06-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20260518_2049'),
        ('admission', '0005_auto_20260511_1723'),
        ('staff', '0003_auto_20260608_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to='admission.admission')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.branch')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.organization')),
            ],
            options={
                'ordering': ['-login_datetime'],
            },
        ),
    ]
