"""
Django settings for wims_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@^k%cy@)cgpxn_p8jyoc%6*pe=obk7pj6sr7jttc+&2g)l_yi9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['wims.revisetoexcel.com','www.wims.revisetoexcel.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    "rest_framework_simplejwt.token_blacklist",
    'users',
    'core',
    'elearning_settings',
    "settings_app",
    'master',
    'staff',
    'course',
    'student_details',
    'admission',
    'fee_details',
    'assignment',
    'reports',
    'drf_yasg',
    
]




REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # or IsAuthenticated
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.JWTWithSessionAuthentication",
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    "core.middleware.ClientMiddleware",   # ✅ HERE

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]



# Recommended security (set HTTPS in production)
SESSION_COOKIE_SECURE = True          # only over HTTPS
CSRF_COOKIE_SECURE = True             # only over HTTPS
SESSION_COOKIE_SAMESITE = "Lax"       # adjust as needed
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # default OK






CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'wims_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wims_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'wims_dbnew',
#         'USER': 'wims_user',
#         'PASSWORD': 'warals@123',
#         'HOST': 'localhost',
#         'PORT': '5432',
#         'CONN_MAX_AGE': 60,  
#         'OPTIONS': {
#             'options': ''
#         }
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'wims_dbnew',
        'USER': 'wims_user',
        'PASSWORD': 'wims_pass',
        'HOST': 'localhost',
        'PORT': '5432',
        'CONN_MAX_AGE': 60,  
        'OPTIONS': {
            'options': ''
        }
    } 
}




TENANT_APPS = [
    "contenttypes",
    "auth",
    "users",
    "admin",
    "sessions",
    "core",
    "master",
    "course",
    "staff",
    "admission",
    "student_details",
    "fee_details",
    "assignment",
    "elearning_settings",
]

# apps that live only in the shared DB (default)
SHARED_APPS = [
    "core",
    "elearning_settings",
]
DATABASE_ROUTERS = ["core.dbrouter.ClientDBRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=10),   # ⏳ adjust as needed
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
    "ROTATE_REFRESH_TOKENS": False,   # keep refresh token same on refresh
    "BLACKLIST_AFTER_ROTATION": True,   # if you rotate refresh tokens

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",

    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False, # Disable session auth to force JWT
    'JSON_EDITOR': True,
}
