# Generated by Django 3.2.15 on 2026-04-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_code', models.CharField(max_length=50, unique=True)),
                ('enquiry_date', models.DateField()),
                ('candidate_name', models.CharField(max_length=100)),
                ('aadhar_card_no', models.CharField(blank=True, max_length=20)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alternate_mobile_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('refer_name', models.CharField(blank=True, max_length=100)),
                ('refer_email', models.EmailField(blank=True, max_length=254)),
                ('refer_phone', models.CharField(blank=True, max_length=15)),
                ('send_mail', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('schedule_demo', models.BooleanField(default=False)),
                ('demo_date', models.DateField(blank=True, null=True)),
                ('demo_time', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('remark', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateField()),
                ('candidate_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('aadhar_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session_fy', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='registration_pics/')),
                ('send_sms', models.BooleanField(default=False)),
                ('send_mail', models.BooleanField(default=False)),
                ('whatsapp', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.batch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.branch')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.country')),
                ('courses', models.ManyToManyField(to='course.Course')),
            ],
        ),
    ]
