# Generated by Django 3.2.15 on 2026-04-16 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('master', '0001_initial'),
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_details.enquiry'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.nationality'),
        ),
        migrations.AddField(
            model_name='registration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.organization'),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.state'),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='enquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='student_details.enquiry'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.status'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='demo_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.batch'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='demo_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_course', to='course.course'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='demo_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_faculty', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.source'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='followup_medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.followupmedium'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.nationality'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.status'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
