# Generated by Django 3.2.15 on 2026-05-21 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20260512_1634'),
        ('course', '0001_initial'),
        ('master', '0002_auto_20260518_2049'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_details', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryfollowup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='confirmed_for_joining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_followups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='demo_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='demo_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.batch'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='demo_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_demo_course', to='course.course'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='demo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='demo_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_demo_faculty', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='demo_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='followup_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.followupmedium'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='interest_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.interestlevel'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='schedule_demo_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_followups_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enquiryfollowup',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='student_details.enquiry'),
        ),
        migrations.AlterField(
            model_name='enquiryfollowup',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquiryfollowup',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.status'),
        ),
    ]
