# Generated by Django 3.2.15 on 2026-04-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=36, null=True)),
                ('module', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=10)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Code Prefix',
                'verbose_name_plural': 'Code Prefixes',
            },
        ),
    ]
