# Generated by Django 3.2.15 on 2026-07-06 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
        ('admission', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField()),
                ('fee_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Installment', 'Installment')], max_length=20)),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('extra_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('billing_before_gst', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('kit_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ledger', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('installment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_generations', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_generations', to='course.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.organization')),
                ('payment_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.paymentmethod')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('due_date', models.DateField(db_index=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fee_details.feegeneration')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ledger', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='fee_details.feeinstallment')),
                ('payment_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='FeeMonthlyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('fee_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='fee_details.feegeneration')),
            ],
            options={
                'unique_together': {('fee_generation', 'month', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='feegeneration',
            index=models.Index(fields=['organization', 'branch'], name='fee_details_organiz_33bd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='feegeneration',
            index=models.Index(fields=['is_active'], name='fee_details_is_acti_c76718_idx'),
        ),
    ]
