# Generated by Django 3.2.15 on 2026-04-16 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
        ('fee_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feegeneration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feegeneration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.organization'),
        ),
        migrations.AddField(
            model_name='feegeneration',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.paymentmethod'),
        ),
        migrations.AddField(
            model_name='feegeneration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedeposit',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='fee_details.feeinstallment'),
        ),
        migrations.AddField(
            model_name='feedeposit',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='feegeneration',
            index=models.Index(fields=['organization', 'branch'], name='fee_details_organiz_33bd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='feegeneration',
            index=models.Index(fields=['is_active'], name='fee_details_is_acti_c76718_idx'),
        ),
    ]
