# Generated by Django 3.2.15 on 2026-04-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_details', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeMonthlyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('fee_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='fee_details.feegeneration')),
            ],
            options={
                'unique_together': {('fee_generation', 'month', 'year')},
            },
        ),
    ]
