# Generated by Django 3.2.15 on 2026-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_details', '0003_feemonthlydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feegeneration',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feegeneration',
            name='ledger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feegeneration',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feegeneration',
            name='reference_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feemonthlydetail',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
